import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:share_plus/share_plus.dart';
import 'app_colors.dart';

class GeneratingPlanScreen extends StatefulWidget {
  const GeneratingPlanScreen({super.key});

  @override
  State<GeneratingPlanScreen> createState() => _GeneratingPlanScreenState();
}

class _GeneratingPlanScreenState extends State<GeneratingPlanScreen> {
  /* ---------------- State ---------------- */
  double _progress = 0.6;
  int _currentStep = 2; // 0-indexed
  String _timeRemaining = '10s';
  bool _isReady = false;

  final List<String> _setupSteps = [
    'Calibrating intensity',
    'Analysing meals',
    'Optimising weekly split',
    'Scheduling reminders',
    'Final touches',
  ];

  @override
  void initState() {
    super.initState();
    _simulateProgress();
  }

  void _simulateProgress() {
    Future.delayed(const Duration(seconds: 3), () {
      if (mounted) {
        setState(() {
          _progress = 1.0;
          _currentStep = 4;
          _timeRemaining = '0s';
          _isReady = true;
        });
      }
    });
  }

  /* ---------------- Navigation ---------------- */
  void _applyPlan() => Navigator.pop(context);
  void _adjustInputs() => Navigator.pop(context);

  /* ---------------- Share & Copy ---------------- */
  void _sharePlan() {
    Share.share(
      'My new AI workout plan:\n\n'
      'Push A – 410 kcal\n'
      'Meals – 190g P / 2 250 kcal\n\n'
      'Generated by Lifestyle Twin',
    );
  }

  void _copyPlan() {
    Clipboard.setData(const ClipboardData(
      text: 'Push A – 410 kcal\nMeals – 190g P / 2 250 kcal',
    ));
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Plan copied to clipboard')),
    );
  }

  /* ---------------------------------------------------------- */
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.softGray,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: Container(
          margin: const EdgeInsets.only(left: 16),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(12),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withOpacity(0.1),
                blurRadius: 4,
                offset: const Offset(0, 2),
              ),
            ],
          ),
          child: IconButton(
            icon: const Icon(Icons.arrow_back, color: AppColors.trustBlue),
            onPressed: () => Navigator.pop(context),
          ),
        ),
        title: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Opacity(
              opacity: 0.2,
              child: Image.asset(
                'assets/lifestyle_twin_logo.png',
                height: 28,
                width: 28,
                fit: BoxFit.cover,
              ),
            ),
            const SizedBox(width: 12),
            const Text(
              'Generating Plan',
              style: TextStyle(
                color: AppColors.trustBlue,
                fontWeight: FontWeight.bold,
                fontSize: 20,
              ),
            ),
          ],
        ),
        centerTitle: true,
        actions: [
          IconButton(
            icon: const Icon(Icons.help_outline, color: AppColors.trustBlue),
            onPressed: () => _showHelpDialog(context),
          ),
        ],
      ),
      body: Column(
        children: [
          Expanded(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                children: [
                  /* 1. Status Card */
                  _statusCard(),
                  const SizedBox(height: 20),

                  /* 2. Setup Steps */
                  _stepsCard(),
                  const SizedBox(height: 20),

                  /* 3. Plan Preview (interactive) */
                  _previewCard(),
                  const SizedBox(height: 20),

                  /* 4. Action Buttons */
                  _actionButtons(),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  /* =========================================================
                         UI COMPONENTS
     ========================================================= */
  Widget _statusCard() => Container(
        width: double.infinity,
        padding: const EdgeInsets.all(20),
        decoration: BoxDecoration(
          gradient: LinearGradient(
            colors: [AppColors.primaryTeal, AppColors.trustBlue],
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
          ),
          borderRadius: BorderRadius.circular(20),
        ),
        child: Column(
          children: [
            const Icon(Icons.auto_awesome, color: Colors.white, size: 32),
            const SizedBox(height: 12),
            const Text(
              'Lifestyle Twin is crafting your plan',
              style: TextStyle(
                  fontSize: 20,
                  fontWeight: FontWeight.bold,
                  color: Colors.white),
            ),
            const SizedBox(height: 8),
            const Text(
              'Using your goals, data sources, and preferences to create the perfect plan for you',
              textAlign: TextAlign.center,
              style: TextStyle(fontSize: 14, color: Colors.white70),
            ),
            const SizedBox(height: 20),

            /* Calm Progress Bar */
            ClipRRect(
              borderRadius: BorderRadius.circular(12),
              child: LinearProgressIndicator(
                value: _progress,
                minHeight: 10,
                backgroundColor: Colors.white.withOpacity(0.2),
                valueColor: const AlwaysStoppedAnimation<Color>(Colors.white),
              ),
            ),
            const SizedBox(height: 12),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text('${(_progress * 100).toInt()}% Complete',
                    style: const TextStyle(
                        color: Colors.white, fontWeight: FontWeight.w600)),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                  decoration: BoxDecoration(
                    color: Colors.white.withOpacity(0.2),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Text('Est. $_timeRemaining',
                      style: const TextStyle(
                          color: Colors.white, fontWeight: FontWeight.w600)),
                ),
              ],
            ),
          ],
        ),
      );

  Widget _stepsCard() => Container(
        width: double.infinity,
        padding: const EdgeInsets.all(20),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(20),
          boxShadow: [
            BoxShadow(
              color: Colors.black.withOpacity(0.08),
              spreadRadius: 0,
              blurRadius: 20,
              offset: const Offset(0, 4),
            ),
          ],
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: AppColors.primaryTeal.withOpacity(0.2),
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Icon(Icons.list, color: AppColors.primaryTeal, size: 20),
                ),
                const SizedBox(width: 12),
                const Text(
                  'Setup Progress',
                  style: TextStyle(
                      fontSize: 18,
                      fontWeight: FontWeight.bold,
                      color: AppColors.trustBlue),
                ),
                const Spacer(),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                  decoration: BoxDecoration(
                    color: AppColors.primaryTeal.withOpacity(0.2),
                    borderRadius: BorderRadius.circular(16),
                  ),
                  child: Text(
                    '${_currentStep + 1} of ${_setupSteps.length}',
                    style: const TextStyle(
                        color: AppColors.trustBlue,
                        fontWeight: FontWeight.bold,
                        fontSize: 12),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 16),
            ...List.generate(
              _setupSteps.length,
              (index) => _stepTile(index),
            ),
          ],
        ),
      );

  Widget _stepTile(int index) {
    final isDone = index < _currentStep;
    final isActive = index == _currentStep;
    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: isDone
            ? AppColors.lightMint.withOpacity(0.3)
            : isActive
                ? AppColors.primaryTeal.withOpacity(0.1)
                : AppColors.softGray,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: isDone
              ? AppColors.accentGreen
              : isActive
                  ? AppColors.primaryTeal.withOpacity(0.3)
                  : Colors.transparent,
          width: isDone ? 2 : 1,
        ),
      ),
      child: Row(
        children: [
          Container(
            width: 36,
            height: 36,
            decoration: BoxDecoration(
              color: isDone
                  ? AppColors.accentGreen
                  : isActive
                      ? AppColors.primaryTeal
                      : Colors.grey,
              shape: BoxShape.circle,
            ),
            child: Icon(
              isDone
                  ? Icons.check
                  : isActive
                      ? Icons.sync
                      : Icons.schedule,
              color: Colors.white,
              size: 20,
            ),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  _setupSteps[index],
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 14,
                    color: isDone || isActive
                        ? AppColors.trustBlue
                        : Colors.grey,
                  ),
                ),
                Text(
                  isDone
                      ? 'Completed'
                      : isActive
                          ? 'In Progress'
                          : 'Queued',
                  style: TextStyle(
                    fontSize: 12,
                    color: isDone || isActive
                        ? Colors.grey
                        : Colors.grey.shade400,
                  ),
                ),
              ],
            ),
          ),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
            decoration: BoxDecoration(
              color: isDone
                  ? AppColors.accentGreen.withOpacity(0.1)
                  : isActive
                      ? AppColors.primaryTeal.withOpacity(0.1)
                      : Colors.grey.withOpacity(0.1),
              borderRadius: BorderRadius.circular(12),
            ),
            child: Text(
              isDone
                  ? 'Completed'
                  : isActive
                      ? 'In Progress'
                      : 'Queued',
              style: TextStyle(
                fontSize: 12,
                fontWeight: FontWeight.bold,
                color: isDone
                    ? AppColors.accentGreen
                    : isActive
                        ? AppColors.primaryTeal
                        : Colors.grey,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _previewCard() => Container(
        width: double.infinity,
        padding: const EdgeInsets.all(20),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(20),
          boxShadow: [
            BoxShadow(
              color: Colors.black.withOpacity(0.08),
              spreadRadius: 0,
              blurRadius: 20,
              offset: const Offset(0, 4),
            ),
          ],
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                const Icon(Icons.preview, color: AppColors.trustBlue, size: 20),
                const SizedBox(width: 8),
                const Text(
                  'Plan Preview',
                  style: TextStyle(
                      fontSize: 18,
                      fontWeight: FontWeight.bold,
                      color: AppColors.trustBlue),
                ),
                const Spacer(),
                IconButton(
                  icon: const Icon(Icons.content_copy,
                      color: AppColors.trustBlue, size: 20),
                  onPressed: _copyPlan,
                ),
                IconButton(
                  icon: const Icon(Icons.share,
                      color: AppColors.trustBlue, size: 20),
                  onPressed: _sharePlan,
                ),
              ],
            ),
            const SizedBox(height: 16),
            _previewItem(
              'Today - Push A',
              '410 kcal',
              ['Incline DB Press • 4x10', 'Overhead Press • 3x8', 'Core Finisher'],
              Icons.fitness_center,
              const Color(0xFFE8F5E8),
              const Color(0xFF2D7D32),
            ),
            const SizedBox(height: 12),
            _previewItem(
              'Meals - Target',
              '190g P • 2,250 kcal',
              ['Oats + Greek yogurt', 'Chicken quinoa bowl', 'Salmon + veggies'],
              Icons.restaurant,
              const Color(0xFFFFF3E0),
              const Color(0xFFE65100),
            ),
          ],
        ),
      );

  Widget _previewItem(
    String title,
    String subtitle,
    List<String> bullets,
    IconData icon,
    Color bgColor,
    Color accentColor,
  ) =>
      Container(
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: bgColor,
          borderRadius: BorderRadius.circular(16),
          border: Border.all(color: accentColor.withOpacity(0.2)),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: accentColor.withOpacity(0.1),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Icon(icon, color: accentColor, size: 16),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        title,
                        style: const TextStyle(
                            fontWeight: FontWeight.bold, fontSize: 14),
                      ),
                      Text(
                        subtitle,
                        style: TextStyle(
                            fontSize: 12,
                            color: accentColor,
                            fontWeight: FontWeight.w600),
                      ),
                    ],
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),
            ...bullets.map((b) => Padding(
                  padding: const EdgeInsets.only(bottom: 4),
                  child: Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        width: 4,
                        height: 4,
                        decoration: BoxDecoration(
                          color: accentColor,
                          shape: BoxShape.circle,
                        ),
                      ),
                      const SizedBox(width: 8),
                      Expanded(
                        child: Text(
                          b,
                          style: const TextStyle(
                              fontSize: 13, color: Color(0xFF4B5563)),
                        ),
                      ),
                    ],
                  ),
                )),
          ],
        ),
      );

  Widget _actionButtons() => Container(
        width: double.infinity,
        padding: const EdgeInsets.all(20),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(20),
          boxShadow: [
            BoxShadow(
              color: Colors.black.withOpacity(0.08),
              spreadRadius: 0,
              blurRadius: 20,
              offset: const Offset(0, 4),
            ),
          ],
        ),
        child: Column(
          children: [
            SizedBox(
              width: double.infinity,
              height: 56,
              child: ElevatedButton.icon(
                onPressed: _isReady ? _applyPlan : null,
                icon: _isReady
                    ? const Icon(Icons.check, color: Colors.white)
                    : const SizedBox(
                        width: 20,
                        height: 20,
                        child: CircularProgressIndicator(
                          strokeWidth: 2,
                          valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                        ),
                      ),
                label: Text(_isReady ? 'Apply Plan' : 'Generating…',
                    style: const TextStyle(
                        color: Colors.white,
                        fontWeight: FontWeight.bold,
                        fontSize: 16)),
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppColors.trustBlue,
                  disabledBackgroundColor: AppColors.trustBlue.withOpacity(0.5),
                  elevation: 0,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(16),
                  ),
                ),
              ),
            ),
            const SizedBox(height: 12),
            SizedBox(
              width: double.infinity,
              height: 48,
              child: OutlinedButton(
                onPressed: _adjustInputs,
                style: OutlinedButton.styleFrom(
                  side: const BorderSide(color: AppColors.trustBlue, width: 1.5),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(16),
                  ),
                ),
                child: const Text(
                  'Adjust Inputs',
                  style: TextStyle(
                      color: AppColors.trustBlue,
                      fontWeight: FontWeight.bold,
                      fontSize: 16),
                ),
              ),
            ),
          ],
        ),
      );

  /* ---------------- Helpers ---------------- */
  void _showHelpDialog(BuildContext context) {
    showDialog(
      context: context,
      builder: (_) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        title: const Text('How Plan Generation Works'),
        content: const Text(
          'Your Lifestyle Twin analyses your fitness data, preferences, and goals to create a personalised plan. This usually takes 15–30 seconds.',
        ),
        actions: [
          TextButton(
            onPressed: Navigator.of(context).pop,
            child: const Text('Got it'),
          ),
    ],),);}
}